../../S3_subfft_src/top_s3_kernel.sv
../../S3_subfft_src/ecc_stage4_v5.sv
../rtl/datapath_subfft_v5.sv
../rtl/fft_common.sv
../rtl/twiddle_rom_1024.sv
../rtl/protection_rtl.sv
../rtl/protection_primitives_v5.sv
../rtl/tmr_subfft_merge_stages_v5.sv
../rtl/arithmetic_apply_from_syndrome_643.sv
