name: RTL unit tests

on:
  push:
  pull_request:

jobs:
  testbenches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install simulators
        run: sudo apt-get update && sudo apt-get install -y iverilog verilator
      - name: Run testbenches
        run: make -C tb dup-check lint all cmd-decoder
